package com.pyroblinchik.newsfinder.data.repository

import android.app.Application
import com.pyroblinchik.newsfinder.data.database.dao.NewsDao
import com.pyroblinchik.newsfinder.data.mapper.NewsMapper
import com.pyroblinchik.newsfinder.data.network.factory.NewsApiFactory
import com.pyroblinchik.newsfinder.domain.base.model.FilterNews
import com.pyroblinchik.newsfinder.domain.base.model.News
import com.pyroblinchik.newsfinder.domain.base.model.UserSettings
import com.pyroblinchik.newsfinder.domain.menu.MenuRepository
import okhttp3.MediaType.Companion.toMediaTypeOrNull
import okhttp3.RequestBody
import okhttp3.RequestBody.Companion.toRequestBody
import timber.log.Timber
import javax.inject.Inject

class MenuRepositoryImpl @Inject constructor(
    private val mapper: NewsMapper,
    private val application: Application,
    private val dao: NewsDao,
) : MenuRepository {

    override suspend fun getNewsFeedFromNetwork(filter: FilterNews): List<News> {
//        val result =
//            NewsApiFactory().apiService.getNews(
//                "",
//                "Android",
//                "us",
//                "general",
//                "cnn"
//            )
//
//        val mapResult = mapper.mapNewsDtoModelToEntity(result)
//
//        Timber.e(result.toString())

        var mapResult = ArrayList<News>()
        val news1 = News()
        news1.id = 0
        news1.author = "Michael Djekovich"
        news1.title = "The Nigerian AI artist reimagining a stylish old age"
        news1.description = "Artworks generated by artificial intelligence (AI) have become a source of controversy, but Nigerian filmmaker and artist Malik Afegbua is making a case that it can challenge us to create a better real world - and a more stylish one for older people.\n" +
                "\n" +
                "At first glance, his images look like they were snapped on the edge of a fashion runway, but these models are not actually real people.\n" +
                "\n" +
                "Instead, the pictures are the result of Afegbua's imagination working in conjunction with AI software, showing older-looking models in beautiful clothes.\n" +
                "\n" +
                "He knew he had created something special after he had posted them on social media. Especially after they caught the eye of the Oscar-winning costume designer behind the Black Panther films, Ruth Carter. \"This is so dope!!\" she wrote on Instagram."
        news1.url = "https://www.bbc.com/news/world-africa-64260739"
        news1.source = "BBC News"
        news1.image = "https://ichef.bbci.co.uk/news/976/cpsprodpb/45AF/production/_128293871_e4ba54db-be8e-40df-ac6a-6749ba43497f.jpg.webp"
        news1.category = "technologies"
        news1.language = "eng"
        news1.country = "Nigeria"
        news1.published_at = "2022-08-05T05:47:24+00:00"
        news1.isFavorite = false
        news1.isInHistory = false
        news1.historyGroupId = 0

        val news2 = News()
        news2.id = 0
        news2.author = "Eric Kuperson"
        news2.title = "Apple boss Tim Cook to have pay cut by over 40% this year"
        news2.description = "Apple chief executive Tim Cook will see his annual pay package slashed by more than 40% this year.\n" +
                "\n" +
                "The technology giant says Mr Cook requested the cut after criticism from shareholders.\n" +
                "\n" +
                "Apple's compensation committee awarded him a total \"target compensation\" of \$49m (£45.1m) for 2023.\n" +
                "\n" +
                "Last year the iPhone maker's shares fell sharply in the face of supply chain issues and a global economic slowdown.\n" +
                "\n" +
                "\"The Compensation Committee balanced shareholder feedback, Apple's exceptional performance, and a recommendation from Mr Cook to adjust his compensation in light of the feedback received,\" Apple said in a filing with a US financial watchdog.\n" +
                "\n" +
                "The move will see Mr Cook's annual basic salary unchanged at \$3m, as well as a bonus of up to \$6m." +
                "Last year the iPhone maker's shares fell sharply in the face of supply chain issues and a global economic slowdown.\n" +
                "\n" +
                "\"The Compensation Committee balanced shareholder feedback, Apple's exceptional performance, and a recommendation from Mr Cook to adjust his compensation in light of the feedback received,\" Apple said in a filing with a US financial watchdog.\n" +
                "\n" +
                "The move will see Mr Cook's annual basic salary unchanged at \$3m, as well as a bonus of up to \$6m." +
                "Last year the iPhone maker's shares fell sharply in the face of supply chain issues and a global economic slowdown.\n" +
                "\n" +
                "\"The Compensation Committee balanced shareholder feedback, Apple's exceptional performance, and a recommendation from Mr Cook to adjust his compensation in light of the feedback received,\" Apple said in a filing with a US financial watchdog.\n" +
                "\n" +
                "The move will see Mr Cook's annual basic salary unchanged at \$3m, as well as a bonus of up to \$6m."
        news2.url = "https://www.bbc.com/news/business-64258289"
        news2.source = "BBC News"
        news2.image = "https://ichef.bbci.co.uk/news/976/cpsprodpb/1690C/production/_128282429_timcook.jpg.webp"
        news2.category = "business"
        news2.language = "eng"
        news2.country = "USA"
        news2.published_at = "2022-10-02T10:20:10+00:00"
        news2.isFavorite = false
        news2.isInHistory = false
        news2.historyGroupId = 0

        val news3 = News()
        news3.id = 0
        news3.author = "Eric Kuperson"
        news3.title = "VR headset prices high as Apple bides its time"
        news3.description = "Last week in Las Vegas I boxed, hunted for cute aliens, flew a laser-shooting robot and drew my own masterpiece - all in virtual reality.\n" +
                "\n" +
                "Some of the headsets I used to try out these experiences cost almost twice as much as the smartphone we used to snap the photo above. Arguably they have a lot less functionality, for now at least. So are they worth it?\n" +
                "\n" +
                "HTC's new Vive XR Elite, out next month, will cost £1,299 or \$1,099. Meta's Quest Pro launched a couple of months ago, priced at £1,499 or \$1,499.\n" +
                "\n" +
                "Meta declined to tell us how many it has sold so far, but my guess is not that many. It is aimed at businesses and (wealthy) early-adopters, designed to be a teaser for Meta's vision of the future, rather than a bestseller."
        news3.url = "https://www.bbc.com/news/technology-64237620"
        news3.source = "BBC News"
        news3.image = "https://ichef.bbci.co.uk/news/976/cpsprodpb/9CDD/production/_128275104_screenshot2023-01-12at17.01.59.png.webp"
        news3.category = "technology"
        news3.language = "eng"
        news3.country = "USA"
        news3.published_at = "2022-04-10T03:40:20+00:00"
        news3.isFavorite = false
        news3.isInHistory = false
        news3.historyGroupId = 0

        val news4 = News()
        news4.id = 0
        news4.author = "Michael Djekovich"
        news4.title = "Your pictures on the theme of 'open doors'"
        news4.description = "We asked our readers to send in their best pictures on the theme of \"open doors\". Here is a selection of the photographs we received from around the world."
        news4.url = "https://www.bbc.com/news/in-pictures-64263211"
        news4.source = "BBC News"
        news4.image = "https://ichef.bbci.co.uk/news/976/cpsprodpb/101B0/production/_128286956_07.jpg.webp"
        news4.category = "pictures"
        news4.language = "eng"
        news4.country = "UK"
        news4.published_at = "2022-01-01T02:20:10+00:00"
        news4.isFavorite = false
        news4.isInHistory = false
        news4.historyGroupId = 0

        mapResult = arrayListOf(news1,news2,news3,news4)

        return mapResult
    }

    override suspend fun getNewsHistoryFromDatabase(): List<News> {
        // TODO "|I| get news and sort by dates"
        val listDB = dao.getHistoryNews()
        val list = ArrayList<News>()
        listDB?.forEach {
            list.add(mapper.mapDbModelToEntity(it))
        }
        return list
    }

    override suspend fun addNewsToHistoryDatabase(news: News) {
        // TODO "|I| news upgrade for save to DB"
        dao.insertNews(mapper.mapEntityToDBModel(news))
    }

    override suspend fun getUserSettingsFromDatabase(): UserSettings {
        TODO("|I| get user settings from Shared Preferences")
    }

    override suspend fun updateUserSettingsFromDatabase(settings: UserSettings): UserSettings {
        TODO("|I| save user settings in Shared Preferences")
    }


}
